PREFIX = 'T3_T'
SUFFIX = '.csv'

LOCAL_PATH = -1
VALID_TIMES = {12, 15, 18, 21}

TRUCK_ID_POSITION = -1
TRUCK_ID_EXTENSION_POSITION = 0
DATA = 1


TOTAL_INVALID_BLANK = 'blank'
TOTAL_INVALID_VOID = 'VOID'
TOTAL_INVALID_ERR = 'ERR'
TOTAL_INVALID_ZERO = 0.00
TOTAL_MAXIMUM_VALUE = 20

CSV_NAME = "PROCESSED_TRUCK_DATA.csv"
