FROM python:latest

WORKDIR /streamlit

RUN mkdir /app

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY database.py .
COPY data_processing.py .
COPY charts.py .
COPY streamlit_application.py .

EXPOSE 8501

RUN chmod +x streamlit_application.py

CMD ["streamlit",  "run", "streamlit_application.py", "--server.port=8501"]
